### ISSUE TITLE
Landmarks

### ISSUE THREAD

**Issue by npschipsch** [alinanilson/webdoc#2]
We have a Question concerning the structure of your website. There is different Information About the order of your Landmarks. In the design diagram it is: Contact Us | Tutorials | Services
Whereas in your Home-draftpage it is: Services | Contact Us | Tutorials

We would suggest to use the second option as it is more intuitive.
Would that be okay for you or shall we use the other option?

**Comment by alinanilson** [comment]
Yes, the second option is fine.

**Comment by npschipsch** [comment]
Thx and Merry Christmas.
