### ISSUE TITLE
Logo of the Website

### ISSUE THREAD

**Issue by npschipsch** [alinanilson/webdoc#3]
In the Website description you said, that we should use the Logo in the header and head of the Website.
When you say, we should use it in the head, do you actually mean to use it as Icon for the tab of the page? (as head is only for metadata).

**Comment by npschipsch** [comment]
When we used your second palette, we stumbled across some problems. We tried to adapt your logo a bit to the colors you have Chosen. Would it be okay to use it the following way?

![bbs-logo](https://user-images.githubusercontent.com/45010582/50170028-3e77f900-02ef-11e9-9175-1898d8253e37.png)

For better understanding, we provided you a prototype of some of your Websites to see, what we mean.
You can find it in the website directory in the Code section.

**Comment by alinanilson** [comment]
Your variant of the logo is good, we are ok with you using it.
If you can put it as an icon for the page, it would be great, but this is not necessary.

**Comment by npschipsch** [comment]
Thx and Merry Christmas.
