### ISSUE TITLE
Contact Us - Page

### ISSUE THREAD

**Issue by npschipsch** [alinanilson/webdoc#4]
You asked for forms to order and do Feedback in the Contact Us - page.
Shall there be dummy buttons for orders and feedback? Could you clarify what shall be in those
Forms (minimum requirement information such as name, email, feedbacktext, etc.) and how their layout
should look like?

**Comment by alinanilson** [comment]
This should be the most basic conact forms, containing 2 fields (one for email address and one for the content of the email) and a "send" button. No javascript is required, so the form is not supposed to be functional.
Other layout is up to you.

**Comment by npschipsch** [comment]
Thx and Merry Christmas.
