### ISSUE TITLE
Tutorial site videos

### ISSUE THREAD

**Issue by npschipsch** [alinanilson/webdoc#9]
We have a question regarding the videos in the tutorials site: we thought about downloading the videos to provide them but there is an upload limit of 25 MB for files on GitHub. We wouldn't recommend embedding the videos from YouTube as hotlinking is a bad Habit. If you are okay with it, we would shorten some of the videos to about 5 minutes and search for a proper solution to display the whole video.

Is this alright for now?

**Comment by alinanilson** [comment]
We do not mind embedding the videos from YouTube, but if you think it is more effective to download and shorten them, we are okay with it.
